markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1

expertchoice_url: http://www.expertchoice.com
comparion_url: https://comparion.expertchoice.com
repository: https://github.com/expertchoice/njtpa

collections:
  docs:
    output: true
  contact:
    output: true
  
